### ISSUE TITLE
Bug in macOS Ventura

### ISSUE THREAD

**Issue by laphysique** [subtledoctor/OS-X-Weidu-Launcher#4]
In macOS Ventura the launcher is not working. After selecting a mod for installation, an error `“mwl.command” can’t be opened because (null) is not allowed to open documents in Terminal` pumps up. 

For all previous macOS versions, the launcher works perfectly as a magic!

**Comment by orendt** [comment]
I get this same error. I never tried it before installing Ventura, however.

**Comment by FairyFatale** [comment]
I am presently getting the same issue as @laphysique running MacOS Ventura 13.2.

I have tried changing bin/bash to bin/zsh but that didn't help. I'm pretty certain that this is some manner of permissions error, but I have thus far not been able to engineer a solution.

**Comment by subtledoctor** [comment]
So, for anyone who reported this... thank you! I have done some research and it seems this was a bug in MacOS Ventura itself...? Which suggests that it may have been fixed in later updates of Ventura, or in Sonoma/Sequoia. I will keep investigating, but if anyone gets this error with Sonoma or Sequoia, please let me know so I have more data points. 

As an interim workaround, if anyone is getting this error, it seems that you can download "iTerm," which is an alternative Terminal program, and set that to be the default app for handling .command scripts. See here:

https://community.localwp.com/t/null-is-not-allowed-to-open-documents-in-terminal-when-trying-to-open-site-shell/34977/2

**Comment by subtledoctor** [comment]
Okay I just tried this on MacOS Ventura version 13.3.1, and the MWL works fine. So it seems Apple fixed this some time ago. Closing this issue.
